apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      #nodeSelector:
      #  environment: production
      containers:
        - name: inflate
          image: pnsmiling/phong
          ports:
          - containerPort: 80