
replicas: 1 # for better debugging experience
controller:
  env:
    - name: FEATURE_GATES
      value: Drift=true
    - name: LEADER_ELECT # disable leader election for better debugging / troubleshooting experience
      value: "false"
    # options
    - name: CLUSTER_NAME
      # disable HTTP/2 to reduce ARM throttling on large-scale tests;
      # with this in place write (and read) QPS can be increased too
      #- name: GODEBUG
      #  value: http2client=0

      value: karpenter
    - name: CLUSTER_ENDPOINT
      value: https://karpenter-azrg-aichatbot-n-85c605-e9sk7obm.hcp.eastus.azmk8s.io:443
    - name: KUBELET_BOOTSTRAP_TOKEN
      value: o3t9h1.p1yp5e2s5x5i5vir
    - name: SSH_PUBLIC_KEY
      value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCX6q7gAOmB2N+QV9bgJqdIf9dh3GVS6i1tljE2Ud2T7ldkytzoEhVkV/X4ZnnWNWvqd/bfPQGCYU++iTEWcudHHanMiM1kIjjxwKYfc5WnpgcnaF/RsXVLHwpP6Tz3148n5ZgXAbUiAwJst02HVmCi9YEfPFtp9hbxHZrE7hzY6WvJEiSIlupcXReUFEyOQ1OoEFtEkmnN/hujTDm06GCJTB/3aHZUk1KNv8YRoWil8Ni64JQXKzjNiq45C3ZfZY/kSZ2t8oFFGzXunktHKGwY7Foji2qof9GBNXVr48SEU9mKVd7rY3QHrcxW9DJvOrEPL5qX6M6kpThjmXerYZDx azureuser"
    - name: NETWORK_PLUGIN
      value: "azure"
    - name: NETWORK_POLICY
      value: ""
    - name: VNET_SUBNET_ID
      value: /subscriptions/85c60575-b3f1-4078-8788-5e150fb84555/resourceGroups/MC_AZRG-AICHATBOT-NONPRD-AKS_karpenter_eastus/providers/Microsoft.Network/virtualNetworks/aks-vnet-38005892/subnets/aks-subnet
    - name: NODE_IDENTITIES
      value: /subscriptions/85c60575-b3f1-4078-8788-5e150fb84555/resourcegroups/MC_AZRG-AICHATBOT-NONPRD-AKS_karpenter_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/karpenter-agentpool
    # Azure client settings
    - name: ARM_SUBSCRIPTION_ID
      value: 85c60575-b3f1-4078-8788-5e150fb84555
    - name: LOCATION
      value: eastus
    # settings for managed workload identity
    - name: ARM_USE_CREDENTIAL_FROM_ENVIRONMENT
      value: "true"
    - name: ARM_USE_MANAGED_IDENTITY_EXTENSION
      value: "false"
    - name: ARM_USER_ASSIGNED_IDENTITY_ID
      value: ""
    - name: AZURE_NODE_RESOURCE_GROUP
      value: MC_AZRG-AICHATBOT-NONPRD-AKS_karpenter_eastus
serviceAccount:
  name: karpenter-sa
  annotations:
    azure.workload.identity/client-id: 122a9961-8c52-4cc4-bc95-ec2eb476f003
podLabels:
  azure.workload.identity/use: "true"
